name: test-core
on: [push, pull_request, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: "Testing core..."
      run: |
           flutter test
           cd example
           flutter test
