name: test-third-party-routers
on: [push, pull_request, workflow_dispatch]
jobs:
  drive:
    defaults:
      run:
        working-directory: ./example
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # or: 'dev' or 'beta'
    - run: flutter config --enable-windows-desktop
    - run: flutter pub get
    - run: flutter create .
    - run: flutter test -d windows integration_test/third_party_router_tests.dart
