name: test-core
on: [push, pull_request, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - name: "Testing core..."
      run: |
           flutter test --reporter expanded --coverage
           cd example
           flutter test --reporter expanded --coverage
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info,./example/coverage/lcov.info
        verbose: true
